#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings! #忽略pod警告

target 'Novel' do
  
  #pod 'Ono'
  
  pod 'HBDNavigationBar'
  
  pod 'Masonry'
  
  pod 'UITableView+FDTemplateLayoutCell'
  
  pod 'YYModel'
  pod 'YYCategories'
  pod 'YYText'
  
  pod 'SDWebImage'
  pod 'SDWebImage/GIF'
  
  pod 'ReactiveObjC'
  
  pod 'YTKNetwork'
  
  pod 'MJRefresh'
  
  pod 'MBProgressHUD'
  
  pod 'FDFullscreenPopGesture'
  
  pod 'WMPageController'
  
  pod 'TTGTagCollectionView'
  
  #微信数据库
  pod 'WCDB'
  
end
